
name: myapp-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: increment version  
      run: bc <<< "1 + $(<./Version)" > ./Version    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mastashoff/myapp:v$(cat ./Version)
      
    - name: login
      run: |
        echo {{ github.event_name }}
        docker login --username "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_TOKEN"
      if: github.event_name == 'push'
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.MYAPP_DOCKER_USER }}
        DOCKER_TOKEN: ${{ secrets.MYAPP_DOCKER_TOKEN }}
    
    - name: push to docker hub  
      run: docker push -a mastashoff/myapp
        
    - name: git push 
      run: |
       git config --global user.email 'mastashoff@gmail.com'
       git config --global user.name 'Yury Y'
       git commit -am 'Upgrade myapp ${{ steps.image.outputs.tag }}' && git push
      
      
      
      
      
