
name: myapp-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: increment version  
      run: bc <<< "1 + $(<./Version)" > ./Version    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mastashoff/myapp:v$(cat ./Version)
    - name: push to docker hub  
      run: docker push -a mastashoff/myapp
      
      
    # login
    - run: |
        docker login ghcr.io --username $USERNAME --password-stdin <<< "$PASSWORD"
        docker login quay.io --username "$DOCKER_USERNAME" --password-stdin <<< "$DOCKER_TOKEN"
      if: github.event_name == 'push'
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ secrets.RELEASE_QUAY_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.RELEASE_QUAY_TOKEN }}
        
        
    #git push 
      git config --global user.email 'ci@argoproj.com'
      git config --global user.name 'CI'
      git commit -am 'Upgrade argocd to ${{ steps.image.outputs.tag }}' && git push
      
      
      
      
      
