
name: myapp-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: shell commands
      run: |
        echo "Hello ${{ github.repository }}",
        
    - name: list files
      run: ls -la
