
name: myapp-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: shell commands
      run: |
        echo "Hello ${{ github.repository }}"
    - name: list and cat
      run: | 
        ls -la
        cat ./Version
    - name: increment version  
      run: bc <<< "1 + $(<./Version)" > ./Version  
    - name: cat new Version
      run: cat ./Version  
