
name: myapp-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: increment version  
      run: bc <<< "1 + $(<./Version)" > ./Version    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mastashoff/myapp:$(cat ./Version)
    - name: push to docker hub  
      run: docker push -a mastashoff/myapp
      
      
      
      
      
